#-------------------------------------------------------------------------------
# Name:        module1
# Purpose:      Writing geometries
#
# Author:      954522
#
# Created:     25/02/2026
# Copyright:   (c) 954522 2026
# Licence:     <your licence>
#-------------------------------------------------------------------------------

#import all required module
import arcpy, fileinput, string

#set the workspace location to store the new shapefile
from arcpy import env
env.workspace=r"C:\GEOS456\Module4"
outpath=env.workspace #store the same path for the 2 outputs


#define the feature class that we are going to create
newfc="NewPolyline.shp"

#create the shapefile using the createfeature class tool
#spatial reference default to unknown
arcpy.CreateFeatureclass_management(outpath, newfc, "Polyline")

#define the text file that stores the coodinates of the vertices to the new feature
inFile="C:\GEOS456\Module4\coordinates.txt"

#incorporate the Insert Cursor using the SHAPE@ geometry token
#SHAPE@ allows us to insert full geometry objects (not just the XY fields)
icursor=arcpy.da.InsertCursor(newfc, ["SHAPE@"])

#create an array to store multiple point objects (vertices)
array=arcpy.Array()

#loop through the text file
for line in fileinput.input(inFile):

    #split the columns apart using the delimiter in the text file (white space)
    ID, X, Y = str.split(line, " ")


    #assign the XY to the new feature

    array.add(arcpy.Point(X, Y))

    #apply the changes to the insert cursor
    icursor.insertRow([arcpy.Polyline(array)])

#close the text file
fileinput.close()

#remove locks that are generated by the insert cursor
del icursor

